# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0002_auto_20161025_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('date_added', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ManyToManyField(related_name='wishlist', to='login_app.Person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Person')),
            ],
        ),
    ]
